apiVersion: v1
kind: Namespace
metadata:
  name: tenant-john-doe
---
apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: green-tea-6831
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: green-tea
    namespace: workspace-tea
  tenant.crownlabs.polito.it/TenantRef:
    name: john.doe
